using System;
using System.Linq;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace ForgeBench
{
    public sealed class MaintenancePanel : MonoBehaviour
    {
        private static MaintenancePanel instance;private GameObject root;private RectTransform content;private Font font;
        public static void Open(){if(instance==null){GameObject g=new GameObject("ForgeBench_MaintenancePanel");DontDestroyOnLoad(g);instance=g.AddComponent<MaintenancePanel>();}instance.Show();}
        public static void RefreshIfOpen(){if(instance!=null&&instance.root!=null&&instance.root.activeSelf)instance.Refresh();}
        private void Awake(){if(instance!=null&&instance!=this){Destroy(gameObject);return;}instance=this;DontDestroyOnLoad(gameObject);font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");EnsureEventSystem();Build();root.SetActive(false);}private void Update(){if(root!=null&&root.activeSelf&&Input.GetKeyDown(KeyCode.Escape)&&!Application.isMobilePlatform)Close();}
        private void Show(){root.SetActive(true);Cursor.lockState=CursorLockMode.None;MobileInputState.Move=Vector2.zero;Refresh();}private void Close(){root.SetActive(false);Cursor.lockState=CursorLockMode.Locked;}
        private void Build(){root=new GameObject("MaintenanceRoot",typeof(RectTransform));root.transform.SetParent(transform,false);Canvas c=root.AddComponent<Canvas>();c.renderMode=RenderMode.ScreenSpaceOverlay;c.sortingOrder=25390;CanvasScaler sc=root.AddComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1920,1080);sc.matchWidthOrHeight=.5f;root.AddComponent<GraphicRaycaster>();GameObject bg=UI("BG",root.transform);Stretch(bg.GetComponent<RectTransform>());bg.AddComponent<Image>().color=new Color(.014f,.020f,.029f,.995f);GameObject panel=UI("Panel",bg.transform);RectTransform pr=panel.GetComponent<RectTransform>();pr.anchorMin=new Vector2(.055f,.05f);pr.anchorMax=new Vector2(.945f,.95f);pr.offsetMin=pr.offsetMax=Vector2.zero;panel.AddComponent<Image>().color=new Color(.052f,.064f,.08f,1f);GameObject header=UI("Header",panel.transform);RectTransform hr=header.GetComponent<RectTransform>();hr.anchorMin=new Vector2(0,1);hr.anchorMax=new Vector2(1,1);hr.pivot=new Vector2(.5f,1);hr.sizeDelta=new Vector2(0,84);hr.anchoredPosition=Vector2.zero;header.AddComponent<Image>().color=new Color(.072f,.087f,.105f,1f);Text title=Text("MAINTENANCE / RELIABILITY",header.transform,30,TextAnchor.MiddleLeft,Color.white);RectTransform tr=title.rectTransform;tr.anchorMin=new Vector2(.025f,0);tr.anchorMax=new Vector2(.82f,1);tr.offsetMin=tr.offsetMax=Vector2.zero;Button close=Button("✕",header.transform,new Color(.55f,.11f,.12f,1f),Close);RectTransform xr=close.GetComponent<RectTransform>();xr.anchorMin=new Vector2(.91f,.16f);xr.anchorMax=new Vector2(.975f,.84f);xr.offsetMin=xr.offsetMax=Vector2.zero;GameObject scrollGo=UI("Scroll",panel.transform);RectTransform sr=scrollGo.GetComponent<RectTransform>();sr.anchorMin=new Vector2(.02f,.025f);sr.anchorMax=new Vector2(.98f,.90f);sr.offsetMin=sr.offsetMax=Vector2.zero;ScrollRect scroll=scrollGo.AddComponent<ScrollRect>();scroll.horizontal=false;scroll.scrollSensitivity=42f;GameObject viewport=UI("Viewport",scrollGo.transform);Stretch(viewport.GetComponent<RectTransform>());viewport.AddComponent<Image>().color=new Color(.024f,.032f,.042f,.78f);Mask mask=viewport.AddComponent<Mask>();mask.showMaskGraphic=false;scroll.viewport=viewport.GetComponent<RectTransform>();GameObject body=UI("Content",viewport.transform);content=body.GetComponent<RectTransform>();content.anchorMin=new Vector2(0,1);content.anchorMax=new Vector2(1,1);content.pivot=new Vector2(.5f,1);content.sizeDelta=new Vector2(0,500);VerticalLayoutGroup vg=body.AddComponent<VerticalLayoutGroup>();vg.padding=new RectOffset(20,20,18,22);vg.spacing=11;vg.childControlHeight=true;vg.childForceExpandHeight=false;vg.childControlWidth=true;vg.childForceExpandWidth=true;ContentSizeFitter fit=body.AddComponent<ContentSizeFitter>();fit.verticalFit=ContentSizeFitter.FitMode.PreferredSize;scroll.content=content;}
        private void Refresh(){if(content==null)return;for(int i=content.childCount-1;i>=0;i--)Destroy(content.GetChild(i).gameObject);GameRuntime g=GameRuntime.Instance;MachineState m=g?.ActiveMachine;Heading("MAINTENANCE / RELIABILITY",m==null?"No active device":m.displayName+" · day "+g.State.day);if(g==null||m==null){Card("NO DEVICE","Accept a contract and move a device to the bench.",new Color(.95f,.42f,.22f,1f));return;}MaintenanceState s=m.maintenance??new MaintenanceState();Card("SERVICE STATE","Device dust "+Mathf.RoundToInt(m.dust*100)+"% · filter dust "+Mathf.RoundToInt(s.filterDust*100)+"%\nThermal paste age "+s.thermalPasteAgeDays+" days · service age "+s.serviceAgeDays+" days · corrosion "+Mathf.RoundToInt(s.corrosion*100)+"%\nCleaning cycles "+s.cleaningCycles+" · ESD incident "+(s.esdIncident?"YES":"NO"),s.filterDust>.65f||s.corrosion>.25f?new Color(.95f,.48f,.18f,1f):new Color(.20f,.82f,.48f,1f));Button service=Button("RUN PREVENTIVE MAINTENANCE",content,new Color(.08f,.50f,.70f,1f),()=>{g.RunPreventiveMaintenance();Refresh();});service.gameObject.AddComponent<LayoutElement>().preferredHeight=58;Section("INSTALLED COMPONENT HEALTH");foreach(string id in Installed(m)){ItemInstance it=g.Inventory.Get(id);HardwareDefinition d=g.Inventory.Def(it);if(it==null||d==null)continue;float risk=(1f-it.condition)*.6f+it.wear*.3f+it.dust*.1f;Color c=risk>.45f||it.fault!=FaultType.None||it.damage!=DamageType.None?new Color(.95f,.36f,.22f,1f):risk>.22f?new Color(.95f,.70f,.22f,1f):Color.white;Card(d.brand+" "+d.model,"Condition "+Mathf.RoundToInt(it.condition*100)+"% · wear "+Mathf.RoundToInt(it.wear*100)+"% · dust "+Mathf.RoundToInt(it.dust*100)+"% · last temp "+it.lastTempC.ToString("0")+"°C\nFault "+it.fault+" · damage "+it.damage+(d.category==PartCategory.Storage?" · writes "+it.writtenGB.ToString("0.0")+" GB · reads "+it.readGB.ToString("0.0")+" GB":""),c);}Section("DEVICE HISTORY");foreach(string line in m.history.AsEnumerable().Reverse().Take(18))Card(line,"",Color.white);}
        private static string[] Installed(MachineState m){return new[]{m.caseItemId,m.motherboardItemId,m.cpuItemId,m.gpuItemId,m.psuItemId,m.coolerItemId}.Concat(m.ramItemIds??new System.Collections.Generic.List<string>()).Concat(m.storageItemIds??new System.Collections.Generic.List<string>()).Concat(m.fanItemIds??new System.Collections.Generic.List<string>()).Where(x=>!string.IsNullOrEmpty(x)).ToArray();}
        private void Heading(string a,string b){Text t=Block(a,32,Color.white,55);t.fontStyle=FontStyle.Bold;Block(b,19,new Color(.56f,.65f,.73f,1f),38);}private void Section(string a){Text t=Block(a,22,new Color(.10f,.64f,.92f,1f),42);t.fontStyle=FontStyle.Bold;}private void Card(string title,string sub,Color c){GameObject g=UI("Card",content);g.AddComponent<Image>().color=new Color(.095f,.115f,.145f,1f);VerticalLayoutGroup v=g.AddComponent<VerticalLayoutGroup>();v.padding=new RectOffset(18,18,11,12);v.spacing=4;v.childControlHeight=true;v.childForceExpandHeight=false;Text a=Text(title,g.transform,21,TextAnchor.MiddleLeft,c);a.fontStyle=FontStyle.Bold;if(!string.IsNullOrEmpty(sub)){Text b=Text(sub,g.transform,17,TextAnchor.UpperLeft,new Color(.66f,.73f,.80f,1f));b.horizontalOverflow=HorizontalWrapMode.Wrap;b.verticalOverflow=VerticalWrapMode.Overflow;}}private Text Block(string value,int size,Color c,float height){Text t=Text(value,content,size,TextAnchor.MiddleLeft,c);LayoutElement l=t.gameObject.AddComponent<LayoutElement>();l.preferredHeight=height;return t;}private Button Button(string label,Transform p,Color c,Action a){GameObject g=UI("Button_"+label,p);Image i=g.AddComponent<Image>();i.color=c;Button b=g.AddComponent<Button>();b.targetGraphic=i;if(a!=null)b.onClick.AddListener(()=>a());Text t=Text(label,g.transform,16,TextAnchor.MiddleCenter,Color.white);Stretch(t.rectTransform,5);t.raycastTarget=false;return b;}private Text Text(string value,Transform p,int size,TextAnchor align,Color c){GameObject g=UI("Text",p);Text t=g.AddComponent<Text>();t.font=font;t.text=value;t.fontSize=size;t.alignment=align;t.color=c;t.raycastTarget=false;return t;}private GameObject UI(string n,Transform p){GameObject g=new GameObject(n,typeof(RectTransform));g.transform.SetParent(p,false);return g;}private static void Stretch(RectTransform r,float i=0){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=new Vector2(i,i);r.offsetMax=new Vector2(-i,-i);}private static void EnsureEventSystem(){if(FindAnyObjectByType<EventSystem>()!=null)return;GameObject e=new GameObject("EventSystem");e.AddComponent<EventSystem>();e.AddComponent<StandaloneInputModule>();DontDestroyOnLoad(e);}
    }
}
