using System;
using System.Linq;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace ForgeBench
{
    public sealed class StaffRosterPanel : MonoBehaviour
    {
        private static StaffRosterPanel instance;private GameObject root;private RectTransform content;private Font font;
        public static void Open(){if(instance==null){GameObject g=new GameObject("ForgeBench_StaffRosterPanel");DontDestroyOnLoad(g);instance=g.AddComponent<StaffRosterPanel>();}instance.Show();}
        public static void RefreshIfOpen(){if(instance!=null&&instance.root!=null&&instance.root.activeSelf)instance.Refresh();}
        private void Awake(){if(instance!=null&&instance!=this){Destroy(gameObject);return;}instance=this;DontDestroyOnLoad(gameObject);font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");EnsureEventSystem();Build();root.SetActive(false);}private void Update(){if(root!=null&&root.activeSelf&&Input.GetKeyDown(KeyCode.Escape)&&!Application.isMobilePlatform)Close();}
        private void Show(){root.SetActive(true);Cursor.lockState=CursorLockMode.None;MobileInputState.Move=Vector2.zero;Refresh();}private void Close(){root.SetActive(false);Cursor.lockState=CursorLockMode.Locked;}
        private void Build(){root=new GameObject("StaffRosterRoot",typeof(RectTransform));root.transform.SetParent(transform,false);Canvas c=root.AddComponent<Canvas>();c.renderMode=RenderMode.ScreenSpaceOverlay;c.sortingOrder=25380;CanvasScaler sc=root.AddComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1920,1080);sc.matchWidthOrHeight=.5f;root.AddComponent<GraphicRaycaster>();GameObject bg=UI("BG",root.transform);Stretch(bg.GetComponent<RectTransform>());bg.AddComponent<Image>().color=new Color(.014f,.020f,.029f,.995f);GameObject panel=UI("Panel",bg.transform);RectTransform pr=panel.GetComponent<RectTransform>();pr.anchorMin=new Vector2(.055f,.05f);pr.anchorMax=new Vector2(.945f,.95f);pr.offsetMin=pr.offsetMax=Vector2.zero;panel.AddComponent<Image>().color=new Color(.052f,.064f,.08f,1f);GameObject header=UI("Header",panel.transform);RectTransform hr=header.GetComponent<RectTransform>();hr.anchorMin=new Vector2(0,1);hr.anchorMax=new Vector2(1,1);hr.pivot=new Vector2(.5f,1);hr.sizeDelta=new Vector2(0,84);hr.anchoredPosition=Vector2.zero;header.AddComponent<Image>().color=new Color(.072f,.087f,.105f,1f);Text title=Text("STAFF ROSTER / TRAINING",header.transform,30,TextAnchor.MiddleLeft,Color.white);RectTransform tr=title.rectTransform;tr.anchorMin=new Vector2(.025f,0);tr.anchorMax=new Vector2(.82f,1);tr.offsetMin=tr.offsetMax=Vector2.zero;Button close=Button("✕",header.transform,new Color(.55f,.11f,.12f,1f),Close);RectTransform xr=close.GetComponent<RectTransform>();xr.anchorMin=new Vector2(.91f,.16f);xr.anchorMax=new Vector2(.975f,.84f);xr.offsetMin=xr.offsetMax=Vector2.zero;GameObject scrollGo=UI("Scroll",panel.transform);RectTransform sr=scrollGo.GetComponent<RectTransform>();sr.anchorMin=new Vector2(.02f,.025f);sr.anchorMax=new Vector2(.98f,.90f);sr.offsetMin=sr.offsetMax=Vector2.zero;ScrollRect scroll=scrollGo.AddComponent<ScrollRect>();scroll.horizontal=false;scroll.scrollSensitivity=42f;GameObject viewport=UI("Viewport",scrollGo.transform);Stretch(viewport.GetComponent<RectTransform>());viewport.AddComponent<Image>().color=new Color(.024f,.032f,.042f,.78f);Mask mask=viewport.AddComponent<Mask>();mask.showMaskGraphic=false;scroll.viewport=viewport.GetComponent<RectTransform>();GameObject body=UI("Content",viewport.transform);content=body.GetComponent<RectTransform>();content.anchorMin=new Vector2(0,1);content.anchorMax=new Vector2(1,1);content.pivot=new Vector2(.5f,1);content.sizeDelta=new Vector2(0,500);VerticalLayoutGroup vg=body.AddComponent<VerticalLayoutGroup>();vg.padding=new RectOffset(20,20,18,22);vg.spacing=11;vg.childControlHeight=true;vg.childForceExpandHeight=false;vg.childControlWidth=true;vg.childForceExpandWidth=true;ContentSizeFitter fit=body.AddComponent<ContentSizeFitter>();fit.verticalFit=ContentSizeFitter.FitMode.PreferredSize;scroll.content=content;}
        private void Refresh(){if(content==null)return;for(int i=content.childCount-1;i>=0;i--)Destroy(content.GetChild(i).gameObject);StaffRosterService s=StaffRosterDirector.Instance?.Service;GameRuntime g=GameRuntime.Instance;if(s==null||g==null){Heading("STAFF ROSTER","Initializing persistent team state…");return;}Heading("STAFF ROSTER / TRAINING",s.State.members.Count+" employee(s) · payroll $"+(g.State.workshop.helperStaff*18+g.State.workshop.specialistStaff*32)+" / day");Card("ROLE COVERAGE","Receiving "+s.Assigned(StaffRole.Receiving)+" · Assembly "+s.Assigned(StaffRole.Assembly)+" · Diagnostics "+s.Assigned(StaffRole.Diagnostics)+" · Board repair "+s.Assigned(StaffRole.BoardRepair)+" · Network "+s.Assigned(StaffRole.Network)+" · Customer desk "+s.Assigned(StaffRole.CustomerDesk),Color.white);foreach(StaffMemberState m in s.State.members.OrderByDescending(x=>x.specialist).ThenByDescending(x=>x.skill))Member(m);if(s.State.members.Count==0)Card("NO STAFF","Hire helpers or specialists from Workshop Management. The roster is synchronized automatically.",Color.white);}
        private void Member(StaffMemberState m){Color status=m.fatigue>.80f?new Color(.95f,.35f,.24f,1f):m.morale<.45f?new Color(.95f,.64f,.20f,1f):m.specialist?new Color(.52f,.38f,.92f,1f):new Color(.20f,.80f,.48f,1f);GameObject card=UI("Staff_"+m.staffId,content);card.AddComponent<Image>().color=new Color(.095f,.115f,.145f,1f);VerticalLayoutGroup v=card.AddComponent<VerticalLayoutGroup>();v.padding=new RectOffset(16,16,10,12);v.spacing=7;v.childControlHeight=true;v.childForceExpandHeight=false;Text title=Text(m.name+" · "+m.staffId+(m.specialist?" · SPECIALIST":" · HELPER"),card.transform,21,TextAnchor.MiddleLeft,status);title.fontStyle=FontStyle.Bold;Text detail=Text("Role "+m.role+" · skill "+m.skill+"/5 · morale "+Mathf.RoundToInt(m.morale*100)+"% · fatigue "+Mathf.RoundToInt(m.fatigue*100)+"% · days "+m.daysEmployed+"\nCertifications: "+(m.certifications.Count==0?"none":string.Join(", ",m.certifications)),card.transform,16,TextAnchor.UpperLeft,new Color(.65f,.73f,.80f,1f));detail.horizontalOverflow=HorizontalWrapMode.Wrap;detail.verticalOverflow=VerticalWrapMode.Overflow;GameObject actions=UI("Actions",card.transform);HorizontalLayoutGroup h=actions.AddComponent<HorizontalLayoutGroup>();h.spacing=7;h.childControlHeight=true;h.childForceExpandHeight=true;h.childForceExpandWidth=true;LayoutElement al=actions.AddComponent<LayoutElement>();al.preferredHeight=54;string id=m.staffId;AddAction(actions.transform,"TRAIN",()=>StaffRosterDirector.Instance?.Train(id),new Color(.15f,.42f,.65f,1f));foreach(StaffRole role in Enum.GetValues(typeof(StaffRole))){StaffRole captured=role;if(role==m.role)continue;if(!m.specialist&&role==StaffRole.BoardRepair)continue;AddAction(actions.transform,Short(role),()=>StaffRosterDirector.Instance?.Assign(id,captured),new Color(.18f,.24f,.30f,1f));}}
        private static string Short(StaffRole r){switch(r){case StaffRole.Receiving:return"RECEIVE";case StaffRole.Assembly:return"ASSEMBLY";case StaffRole.Diagnostics:return"DIAG";case StaffRole.BoardRepair:return"BOARD";case StaffRole.Network:return"NETWORK";default:return"CUSTOMERS";}}
        private void AddAction(Transform p,string label,Action a,Color c){Button b=Button(label,p,c,()=>{a?.Invoke();Refresh();});LayoutElement le=b.gameObject.AddComponent<LayoutElement>();le.flexibleWidth=1;}
        private void Heading(string a,string b){Text t=Block(a,32,Color.white,55);t.fontStyle=FontStyle.Bold;Block(b,19,new Color(.56f,.65f,.73f,1f),38);}private void Card(string title,string sub,Color c){GameObject g=UI("Card",content);g.AddComponent<Image>().color=new Color(.095f,.115f,.145f,1f);VerticalLayoutGroup v=g.AddComponent<VerticalLayoutGroup>();v.padding=new RectOffset(18,18,11,12);v.spacing=4;v.childControlHeight=true;v.childForceExpandHeight=false;Text a=Text(title,g.transform,21,TextAnchor.MiddleLeft,c);a.fontStyle=FontStyle.Bold;Text b=Text(sub,g.transform,17,TextAnchor.UpperLeft,new Color(.66f,.73f,.80f,1f));b.horizontalOverflow=HorizontalWrapMode.Wrap;b.verticalOverflow=VerticalWrapMode.Overflow;}private Text Block(string value,int size,Color c,float height){Text t=Text(value,content,size,TextAnchor.MiddleLeft,c);LayoutElement l=t.gameObject.AddComponent<LayoutElement>();l.preferredHeight=height;return t;}private Button Button(string label,Transform p,Color c,Action a){GameObject g=UI("Button_"+label,p);Image i=g.AddComponent<Image>();i.color=c;Button b=g.AddComponent<Button>();b.targetGraphic=i;if(a!=null)b.onClick.AddListener(()=>a());Text t=Text(label,g.transform,14,TextAnchor.MiddleCenter,Color.white);Stretch(t.rectTransform,4);t.raycastTarget=false;return b;}private Text Text(string value,Transform p,int size,TextAnchor align,Color c){GameObject g=UI("Text",p);Text t=g.AddComponent<Text>();t.font=font;t.text=value;t.fontSize=size;t.alignment=align;t.color=c;t.raycastTarget=false;return t;}private GameObject UI(string n,Transform p){GameObject g=new GameObject(n,typeof(RectTransform));g.transform.SetParent(p,false);return g;}private static void Stretch(RectTransform r,float i=0){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=new Vector2(i,i);r.offsetMax=new Vector2(-i,-i);}private static void EnsureEventSystem(){if(FindAnyObjectByType<EventSystem>()!=null)return;GameObject e=new GameObject("EventSystem");e.AddComponent<EventSystem>();e.AddComponent<StandaloneInputModule>();DontDestroyOnLoad(e);}
    }
}
