using System;
using System.Linq;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace ForgeBench
{
    public sealed class SupplyChainPanel : MonoBehaviour
    {
        private static SupplyChainPanel instance;private GameRuntime game;private GameObject root;private RectTransform content;private Font font;private PartCategory category=PartCategory.CPU;private int page;
        public static void Open(){if(instance==null){GameObject g=new GameObject("ForgeBench_SupplyChainPanel");DontDestroyOnLoad(g);instance=g.AddComponent<SupplyChainPanel>();}instance.Show();}
        private void Awake(){if(instance!=null&&instance!=this){Destroy(gameObject);return;}instance=this;DontDestroyOnLoad(gameObject);font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");EnsureEventSystem();Build();root.SetActive(false);}
        private void Update(){if(root!=null&&root.activeSelf&&Input.GetKeyDown(KeyCode.Escape)&&!Application.isMobilePlatform)Close();}
        private void Show(){game=GameRuntime.Instance;root.SetActive(true);Cursor.lockState=CursorLockMode.None;MobileInputState.Move=Vector2.zero;Refresh();}private void Close(){root.SetActive(false);Cursor.lockState=CursorLockMode.Locked;}
        private void Build(){root=new GameObject("SupplyChainRoot",typeof(RectTransform));root.transform.SetParent(transform,false);Canvas c=root.AddComponent<Canvas>();c.renderMode=RenderMode.ScreenSpaceOverlay;c.sortingOrder=25300;CanvasScaler sc=root.AddComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1920,1080);sc.matchWidthOrHeight=.5f;root.AddComponent<GraphicRaycaster>();GameObject bg=UI("BG",root.transform);Stretch(bg.GetComponent<RectTransform>());bg.AddComponent<Image>().color=new Color(.014f,.021f,.030f,.99f);GameObject panel=UI("Panel",bg.transform);RectTransform pr=panel.GetComponent<RectTransform>();pr.anchorMin=new Vector2(.05f,.05f);pr.anchorMax=new Vector2(.95f,.95f);pr.offsetMin=pr.offsetMax=Vector2.zero;panel.AddComponent<Image>().color=new Color(.05f,.063f,.080f,1f);GameObject header=UI("Header",panel.transform);RectTransform hr=header.GetComponent<RectTransform>();hr.anchorMin=new Vector2(0,1);hr.anchorMax=new Vector2(1,1);hr.pivot=new Vector2(.5f,1);hr.sizeDelta=new Vector2(0,82);hr.anchoredPosition=Vector2.zero;header.AddComponent<Image>().color=new Color(.068f,.084f,.105f,1f);Text title=Text("SUPPLIER NETWORK",header.transform,30,TextAnchor.MiddleLeft,Color.white);RectTransform tr=title.rectTransform;tr.anchorMin=new Vector2(.025f,0);tr.anchorMax=new Vector2(.43f,1);tr.offsetMin=tr.offsetMax=Vector2.zero;Button market=Button("MARKET",header.transform,new Color(.12f,.15f,.19f,1f),()=>{page=0;Refresh();});Place(market,.48f,.16f,.62f,.84f);Button shipments=Button("SHIPMENTS",header.transform,new Color(.12f,.15f,.19f,1f),()=>{page=1;Refresh();});Place(shipments,.63f,.16f,.78f,.84f);Button close=Button("✕",header.transform,new Color(.55f,.11f,.12f,1f),Close);Place(close,.92f,.16f,.978f,.84f);GameObject sg=UI("Scroll",panel.transform);RectTransform sr=sg.GetComponent<RectTransform>();sr.anchorMin=new Vector2(.02f,.025f);sr.anchorMax=new Vector2(.98f,.90f);sr.offsetMin=sr.offsetMax=Vector2.zero;ScrollRect scroll=sg.AddComponent<ScrollRect>();scroll.horizontal=false;scroll.scrollSensitivity=42;GameObject vp=UI("Viewport",sg.transform);Stretch(vp.GetComponent<RectTransform>());Image vi=vp.AddComponent<Image>();vi.color=new Color(.023f,.031f,.042f,.75f);Mask mask=vp.AddComponent<Mask>();mask.showMaskGraphic=false;scroll.viewport=vp.GetComponent<RectTransform>();GameObject body=UI("Content",vp.transform);content=body.GetComponent<RectTransform>();content.anchorMin=new Vector2(0,1);content.anchorMax=new Vector2(1,1);content.pivot=new Vector2(.5f,1);content.sizeDelta=new Vector2(0,500);VerticalLayoutGroup vg=body.AddComponent<VerticalLayoutGroup>();vg.padding=new RectOffset(20,20,18,22);vg.spacing=10;vg.childControlHeight=true;vg.childForceExpandHeight=false;vg.childControlWidth=true;vg.childForceExpandWidth=true;ContentSizeFitter f=body.AddComponent<ContentSizeFitter>();f.verticalFit=ContentSizeFitter.FitMode.PreferredSize;scroll.content=content;}
        private void Refresh(){if(content==null)return;for(int i=content.childCount-1;i>=0;i--)Destroy(content.GetChild(i).gameObject);game=GameRuntime.Instance;if(game==null)return;SupplyChainService s=game.Supply();WorkshopBusinessService b=game.Business();Heading(page==0?"DYNAMIC HARDWARE MARKET":"INBOUND / RECEIVING","Cash $"+game.State.money.ToString("0")+" · warehouse "+b.WarehouseUsed+"/"+b.WarehouseCapacity+" · day "+game.State.day);if(page==0)RenderMarket(s);else RenderShipments(s);}
        private void RenderMarket(SupplyChainService s){PartCategory[] cats={PartCategory.Case,PartCategory.Motherboard,PartCategory.CPU,PartCategory.RAM,PartCategory.GPU,PartCategory.Storage,PartCategory.PSU,PartCategory.Cooler,PartCategory.Fan,PartCategory.Network,PartCategory.Battery,PartCategory.Display};GameObject row=ActionRow();foreach(PartCategory c in cats){PartCategory cc=c;Button btn=Button(c.ToString(),row.transform,c==category?new Color(.08f,.55f,.82f,1f):new Color(.12f,.15f,.19f,1f),()=>{category=cc;Refresh();});LayoutElement le=btn.gameObject.AddComponent<LayoutElement>();le.preferredWidth=118;le.flexibleWidth=1;}Section(category.ToString().ToUpperInvariant());foreach(HardwareDefinition d in s.Market(category,30)){float q=s.Quote(d);string spec=(d.performance>0?"perf "+d.performance+" · ":"")+(d.storageGB>0?d.storageGB+"GB · ":"")+(d.psuWattage>0?d.psuWattage+"W · ":"")+"quality "+d.quality;string id=d.id;MarketRow(d.brand+" "+d.model,spec+" · list $"+d.price.ToString("0")+" · quote $"+q.ToString("0"),()=>game.SupplyOrder(id,1,1),()=>game.SupplyOrder(id,4,0));}}
        private void RenderShipments(SupplyChainService s){var all=game.State.shipments.OrderByDescending(x=>x.orderedDay).ThenByDescending(x=>x.shipmentId).Take(40).ToList();if(all.Count==0){Card("No shipments","Order hardware from the supplier market.",Color.white);return;}foreach(ShipmentState sh in all){string items=string.Join(", ",sh.lines.Select(x=>(game.Catalog.Get(x.definitionId)?.model??x.definitionId)+" ×"+x.quantity));string status=sh.status+" · ordered day "+sh.orderedDay+" · ETA "+sh.deliveryDay+(sh.delayed?" · DELAYED":"")+(sh.wrongItemEvent?" · INSPECTION MISMATCH":"");string id=sh.shipmentId;GameObject card=UI("Shipment",content);card.AddComponent<Image>().color=new Color(.095f,.115f,.145f,1f);HorizontalLayoutGroup h=card.AddComponent<HorizontalLayoutGroup>();h.padding=new RectOffset(16,12,9,9);h.spacing=8;h.childControlHeight=true;h.childForceExpandHeight=true;LayoutElement cl=card.AddComponent<LayoutElement>();cl.preferredHeight=82;GameObject box=UI("Text",card.transform);VerticalLayoutGroup v=box.AddComponent<VerticalLayoutGroup>();v.childForceExpandHeight=false;LayoutElement bl=box.AddComponent<LayoutElement>();bl.flexibleWidth=1;Text a=Text(sh.shipmentId+" · "+status,box.transform,18,TextAnchor.MiddleLeft,Color.white);a.fontStyle=FontStyle.Bold;Text b=Text(items,box.transform,15,TextAnchor.MiddleLeft,new Color(.62f,.70f,.78f,1f));if(sh.status==ShipmentStatus.Delivered){Button receive=Button("RECEIVE",card.transform,new Color(.10f,.54f,.35f,1f),()=>{game.SupplyReceive(id);Refresh();});LayoutElement rl=receive.gameObject.AddComponent<LayoutElement>();rl.preferredWidth=125;if(sh.wrongItemEvent){Button ret=Button("RETURN",card.transform,new Color(.65f,.25f,.10f,1f),()=>{game.SupplyReturnMismatch(id);Refresh();});LayoutElement rt=ret.gameObject.AddComponent<LayoutElement>();rt.preferredWidth=120;}}else if(sh.status==ShipmentStatus.InTransit){Button cancel=Button("CANCEL",card.transform,new Color(.42f,.18f,.18f,1f),()=>{game.SupplyCancel(id);Refresh();});LayoutElement xl=cancel.gameObject.AddComponent<LayoutElement>();xl.preferredWidth=120;}}}
        private void MarketRow(string title,string sub,Action one,Action bulk){GameObject g=UI("MarketRow",content);g.AddComponent<Image>().color=new Color(.095f,.115f,.145f,1f);HorizontalLayoutGroup h=g.AddComponent<HorizontalLayoutGroup>();h.padding=new RectOffset(16,10,8,8);h.spacing=8;h.childControlHeight=true;h.childForceExpandHeight=true;LayoutElement gl=g.AddComponent<LayoutElement>();gl.preferredHeight=72;GameObject tb=UI("Text",g.transform);VerticalLayoutGroup v=tb.AddComponent<VerticalLayoutGroup>();v.childForceExpandHeight=false;LayoutElement tl=tb.AddComponent<LayoutElement>();tl.flexibleWidth=1;Text a=Text(title,tb.transform,19,TextAnchor.MiddleLeft,Color.white);a.fontStyle=FontStyle.Bold;Text b=Text(sub,tb.transform,15,TextAnchor.MiddleLeft,new Color(.63f,.71f,.79f,1f));Button b1=Button("BUY 1",g.transform,new Color(.08f,.50f,.76f,1f),()=>{one();Refresh();});Button b4=Button("BULK 4",g.transform,new Color(.11f,.40f,.58f,1f),()=>{bulk();Refresh();});LayoutElement l1=b1.gameObject.AddComponent<LayoutElement>();l1.preferredWidth=105;LayoutElement l4=b4.gameObject.AddComponent<LayoutElement>();l4.preferredWidth=115;}
        private GameObject ActionRow(){GameObject g=UI("Categories",content);HorizontalLayoutGroup h=g.AddComponent<HorizontalLayoutGroup>();h.spacing=5;h.childControlHeight=true;h.childForceExpandHeight=true;h.childForceExpandWidth=true;LayoutElement l=g.AddComponent<LayoutElement>();l.preferredHeight=56;return g;}private void Heading(string a,string b){Text t=Block(a,32,Color.white,54);t.fontStyle=FontStyle.Bold;Block(b,18,new Color(.56f,.65f,.74f,1f),38);}private void Section(string a){Text t=Block(a,22,new Color(.10f,.64f,.92f,1f),40);t.fontStyle=FontStyle.Bold;}private void Card(string a,string b,Color c){GameObject g=UI("Card",content);g.AddComponent<Image>().color=new Color(.095f,.115f,.145f,1f);VerticalLayoutGroup v=g.AddComponent<VerticalLayoutGroup>();v.padding=new RectOffset(16,16,10,10);v.childForceExpandHeight=false;LayoutElement l=g.AddComponent<LayoutElement>();l.minHeight=68;Text x=Text(a,g.transform,20,TextAnchor.MiddleLeft,c);x.fontStyle=FontStyle.Bold;Text y=Text(b,g.transform,16,TextAnchor.UpperLeft,new Color(.64f,.71f,.79f,1f));}
        private Text Block(string v,int s,Color c,float h){Text t=Text(v,content,s,TextAnchor.MiddleLeft,c);LayoutElement l=t.gameObject.AddComponent<LayoutElement>();l.preferredHeight=h;return t;}private Button Button(string l,Transform p,Color c,Action a){GameObject g=UI("Button_"+l,p);Image i=g.AddComponent<Image>();i.color=c;Button b=g.AddComponent<Button>();b.targetGraphic=i;if(a!=null)b.onClick.AddListener(()=>a());Text t=Text(l,g.transform,14,TextAnchor.MiddleCenter,Color.white);Stretch(t.rectTransform,4);t.raycastTarget=false;return b;}private Text Text(string v,Transform p,int s,TextAnchor a,Color c){GameObject g=UI("Text",p);Text t=g.AddComponent<Text>();t.font=font;t.text=v;t.fontSize=s;t.alignment=a;t.color=c;t.raycastTarget=false;return t;}private GameObject UI(string n,Transform p){GameObject g=new GameObject(n,typeof(RectTransform));g.transform.SetParent(p,false);return g;}private static void Stretch(RectTransform r,float i=0){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=new Vector2(i,i);r.offsetMax=new Vector2(-i,-i);}private static void Place(Component c,float x0,float y0,float x1,float y1){RectTransform r=c.GetComponent<RectTransform>();r.anchorMin=new Vector2(x0,y0);r.anchorMax=new Vector2(x1,y1);r.offsetMin=r.offsetMax=Vector2.zero;}private static void EnsureEventSystem(){if(FindAnyObjectByType<EventSystem>()!=null)return;GameObject e=new GameObject("EventSystem");e.AddComponent<EventSystem>();e.AddComponent<StandaloneInputModule>();DontDestroyOnLoad(e);}
    }
}
