using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace ForgeBench
{
    /// <summary>
    /// Visually expands the physical workshop as the persistent workshop level grows.
    /// Rooms are deterministic procedural geometry: storage, diagnostics, board lab,
    /// liquid/network lab, premium office and master service bay.
    /// </summary>
    public sealed class WorkshopExpansionLayer : MonoBehaviour
    {
        private GameObject root;private GameRuntime game;private int builtLevel=-1;private readonly List<Material> materials=new List<Material>();private Shader shader;private float nextPoll;
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]private static void Install(){if(FindAnyObjectByType<WorkshopExpansionLayer>()!=null)return;GameObject go=new GameObject("ForgeBench_WorkshopExpansionLayer");DontDestroyOnLoad(go);go.AddComponent<WorkshopExpansionLayer>();}
        private IEnumerator Start(){while(GameRuntime.Instance==null||GameRuntime.Instance.State==null||GameRuntime.Instance.World==null)yield return null;game=GameRuntime.Instance;shader=Shader.Find("Universal Render Pipeline/Lit")??Shader.Find("Standard");Rebuild();}
        private void Update(){if(Time.unscaledTime<nextPoll)return;nextPoll=Time.unscaledTime+1f;if(GameRuntime.Instance==null||GameRuntime.Instance.State==null)return;game=GameRuntime.Instance;if(builtLevel!=game.State.workshop.level)Rebuild();}
        private void Rebuild(){if(game==null||game.State==null)return;builtLevel=game.State.workshop.level;if(root!=null)Destroy(root);foreach(Material m in materials)if(m!=null)Destroy(m);materials.Clear();root=new GameObject("WorkshopExpansion_L"+builtLevel);BuildRearHall();if(builtLevel>=2)BuildDiagnosticsWing();if(builtLevel>=3)BuildBoardLab();if(builtLevel>=4)BuildLiquidNetworkWing();if(builtLevel>=5)BuildPremiumOffice();if(builtLevel>=6)BuildMasterBay();}
        private void BuildRearHall(){Material floor=Mat(new Color(.065f,.07f,.078f),.25f,.12f),wall=Mat(new Color(.105f,.12f,.14f),.45f,.12f),trim=Mat(new Color(.03f,.04f,.05f),.34f,.66f),accent=Mat(new Color(.04f,.46f,.72f),.45f,.25f);Box("ExpansionFloor",new Vector3(0,-.14f,7.4f),new Vector3(13.8f,.12f,2.7f),floor);Box("RearWall",new Vector3(0,2.45f,8.7f),new Vector3(13.8f,4.9f,.16f),wall);Box("RearCeiling",new Vector3(0,4.8f,7.4f),new Vector3(13.8f,.14f,2.7f),trim);Box("HallAccent",new Vector3(0,.01f,6.18f),new Vector3(7.0f,.025f,.12f),accent);Label("EXPANSION HALL · LEVEL "+builtLevel,new Vector3(0,4.05f,8.56f),new Vector2(4f,.45f),30);}
        private void BuildDiagnosticsWing(){Material wall=Mat(new Color(.08f,.13f,.15f),.38f,.18f),bench=Mat(new Color(.12f,.14f,.16f),.42f,.65f),screen=Mat(new Color(.02f,.30f,.42f),.6f,.08f);RoomShell("DiagnosticsWing",new Vector3(-5.45f,0,7.4f),new Vector3(2.8f,4.5f,2.45f),wall);Box("DiagBench",new Vector3(-5.45f,.82f,7.75f),new Vector3(2.3f,.12f,.72f),bench);for(int i=0;i<3;i++){Box("Scope"+i,new Vector3(-6.15f+i*.7f,1.22f,7.72f),new Vector3(.42f,.34f,.18f),screen);Cylinder("ProbeA"+i,new Vector3(-6.25f+i*.7f,1.09f,7.30f),new Vector3(.025f,.24f,.025f),Quaternion.Euler(70,0,0),bench);Cylinder("ProbeB"+i,new Vector3(-6.03f+i*.7f,1.09f,7.30f),new Vector3(.025f,.24f,.025f),Quaternion.Euler(70,0,0),bench);}Label("ADVANCED DIAGNOSTICS",new Vector3(-5.45f,3.75f,8.54f),new Vector2(2.4f,.34f),22);}
        private void BuildBoardLab(){Material wall=Mat(new Color(.12f,.10f,.12f),.40f,.15f),bench=Mat(new Color(.08f,.10f,.11f),.45f,.7f),esd=Mat(new Color(.035f,.24f,.20f),.28f,.05f),hot=Mat(new Color(.45f,.12f,.04f),.45f,.45f);RoomShell("BoardLab",new Vector3(-2.55f,0,7.4f),new Vector3(2.6f,4.5f,2.45f),wall);Box("BoardBench",new Vector3(-2.55f,.82f,7.75f),new Vector3(2.15f,.12f,.72f),bench);Box("ESDMat",new Vector3(-2.55f,.90f,7.72f),new Vector3(1.45f,.025f,.52f),esd);Cylinder("MicroscopePost",new Vector3(-3.15f,1.35f,7.72f),new Vector3(.06f,.50f,.06f),Quaternion.identity,bench);Cylinder("MicroscopeHead",new Vector3(-2.90f,1.73f,7.60f),new Vector3(.16f,.30f,.16f),Quaternion.Euler(90,0,0),bench);Box("HotAirStation",new Vector3(-1.85f,1.12f,7.75f),new Vector3(.42f,.35f,.42f),hot);Label("BOARD / MICRO REWORK",new Vector3(-2.55f,3.75f,8.54f),new Vector2(2.4f,.34f),22);}
        private void BuildLiquidNetworkWing(){Material wall=Mat(new Color(.08f,.105f,.13f),.40f,.16f),metal=Mat(new Color(.18f,.20f,.22f),.48f,.75f),coolant=Mat(new Color(.02f,.42f,.65f),.72f,.05f),net=Mat(new Color(.03f,.28f,.16f),.55f,.25f);RoomShell("LiquidNetworkWing",new Vector3(2.05f,0,7.4f),new Vector3(6.2f,4.5f,2.45f),wall);Box("LiquidBench",new Vector3(.85f,.82f,7.75f),new Vector3(2.25f,.12f,.72f),metal);Cylinder("ReservoirDemo",new Vector3(.35f,1.45f,7.70f),new Vector3(.16f,.58f,.16f),Quaternion.identity,coolant);Box("RadiatorDemo",new Vector3(1.15f,1.38f,7.72f),new Vector3(.75f,.95f,.08f),metal);for(int i=0;i<3;i++)Cylinder("RadFan"+i,new Vector3(1.15f,1.03f+i*.34f,7.62f),new Vector3(.14f,.03f,.14f),Quaternion.Euler(90,0,0),metal);Box("Rack",new Vector3(3.65f,1.60f,7.90f),new Vector3(1.65f,2.75f,.65f),metal);for(int u=0;u<7;u++){GameObject server=Box("ServerU"+u,new Vector3(3.65f,.48f+u*.34f,7.53f),new Vector3(1.45f,.25f,.10f),net);if(u==3){WorldInteractable wi=server.AddComponent<WorldInteractable>();wi.label="Open network / NAS specialist bench";wi.priority=25;wi.action=()=>SpecialistRepairPanel.Open(SpecialistPanelMode.Network);}}Label("LIQUID / NETWORK LAB",new Vector3(2.05f,3.75f,8.54f),new Vector2(3.4f,.34f),22);}
        private void BuildPremiumOffice(){Material wall=Mat(new Color(.13f,.12f,.11f),.55f,.10f),wood=Mat(new Color(.28f,.18f,.10f),.62f,.05f),screen=Mat(new Color(.03f,.19f,.31f),.72f,.10f),glass=Mat(new Color(.10f,.22f,.28f),.82f,.06f);RoomShell("PremiumOffice",new Vector3(5.45f,0,7.4f),new Vector3(2.6f,4.5f,2.45f),wall);Box("ExecutiveDesk",new Vector3(5.45f,.80f,7.75f),new Vector3(2.1f,.12f,.76f),wood);Box("WideDisplay",new Vector3(5.45f,1.52f,7.68f),new Vector3(1.60f,.72f,.06f),screen);Box("OfficeGlass",new Vector3(4.28f,2.0f,7.35f),new Vector3(.035f,3.7f,1.75f),glass);GameObject crm=Box("PremiumCRMButton",new Vector3(5.45f,1.08f,7.34f),new Vector3(.55f,.05f,.26f),screen);WorldInteractable wi=crm.AddComponent<WorldInteractable>();wi.label="Open premium customer relations";wi.priority=24;wi.action=()=>CustomerRelationsPanel.Open();Label("PREMIUM SERVICE OFFICE",new Vector3(5.45f,3.75f,8.54f),new Vector2(2.4f,.34f),22);}
        private void BuildMasterBay(){Material dark=Mat(new Color(.025f,.03f,.04f),.38f,.72f),gold=Mat(new Color(.48f,.34f,.08f),.58f,.55f),pad=Mat(new Color(.055f,.075f,.09f),.22f,.08f);Box("MasterPlatform",new Vector3(0,.04f,5.92f),new Vector3(4.5f,.08f,1.6f),pad);for(int x=-1;x<=1;x+=2)Box("MasterColumn",new Vector3(x*2.05f,2.0f,5.92f),new Vector3(.12f,4f,.12f),gold);Box("MasterHeader",new Vector3(0,3.95f,5.92f),new Vector3(4.3f,.12f,.12f),gold);GameObject terminal=Box("MasterConsole",new Vector3(0,1.25f,6.25f),new Vector3(1.3f,.70f,.10f),dark);WorldInteractable i=terminal.AddComponent<WorldInteractable>();i.label="Open master technician certifications";i.priority=30;i.action=()=>ProgressionPanel.Open();Label("MASTER SERVICE BAY",new Vector3(0,3.72f,5.83f),new Vector2(2.8f,.4f),28);}
        private void RoomShell(string n,Vector3 center,Vector3 size,Material wall){Box(n+"Back",center+new Vector3(0,2.2f,size.z*.49f),new Vector3(size.x,4.4f,.10f),wall);Box(n+"Left",center+new Vector3(-size.x*.49f,2.2f,0),new Vector3(.10f,4.4f,size.z),wall);Box(n+"Right",center+new Vector3(size.x*.49f,2.2f,0),new Vector3(.10f,4.4f,size.z),wall);}
        private GameObject Box(string n,Vector3 p,Vector3 s,Material m){GameObject g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(root.transform,true);g.transform.position=p;g.transform.localScale=s;Renderer r=g.GetComponent<Renderer>();if(r!=null)r.sharedMaterial=m;return g;}private GameObject Cylinder(string n,Vector3 p,Vector3 s,Quaternion q,Material m){GameObject g=GameObject.CreatePrimitive(PrimitiveType.Cylinder);g.name=n;g.transform.SetParent(root.transform,true);g.transform.position=p;g.transform.localScale=s;g.transform.rotation=q;Renderer r=g.GetComponent<Renderer>();if(r!=null)r.sharedMaterial=m;return g;}private Material Mat(Color c,float smooth,float metal=0f){Material m=new Material(shader);m.color=c;if(m.HasProperty("_Smoothness"))m.SetFloat("_Smoothness",smooth);if(m.HasProperty("_Metallic"))m.SetFloat("_Metallic",metal);materials.Add(m);return m;}
        private void Label(string text,Vector3 p,Vector2 size,int fs){GameObject go=new GameObject("Label_"+text,typeof(RectTransform),typeof(Canvas));go.transform.SetParent(root.transform,false);go.transform.position=p;go.transform.rotation=Quaternion.Euler(0,180,0);go.transform.localScale=Vector3.one*.01f;Canvas c=go.GetComponent<Canvas>();c.renderMode=RenderMode.WorldSpace;RectTransform rt=go.GetComponent<RectTransform>();rt.sizeDelta=size;GameObject tg=new GameObject("Text",typeof(RectTransform),typeof(UnityEngine.UI.Text));tg.transform.SetParent(go.transform,false);RectTransform tr=tg.GetComponent<RectTransform>();tr.anchorMin=Vector2.zero;tr.anchorMax=Vector2.one;tr.offsetMin=tr.offsetMax=Vector2.zero;UnityEngine.UI.Text t=tg.GetComponent<UnityEngine.UI.Text>();t.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");t.text=text;t.fontSize=fs;t.alignment=TextAnchor.MiddleCenter;t.color=Color.white;}
        private void OnDestroy(){foreach(Material m in materials)if(m!=null)Destroy(m);}
    }
}
