using System;
using System.Linq;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace ForgeBench
{
    public sealed class WorkshopBusinessPanel : MonoBehaviour
    {
        private static WorkshopBusinessPanel instance;
        private GameRuntime game; private GameObject root; private RectTransform content; private Font font; private int page;
        public static void Open(int p=0){if(instance==null){GameObject g=new GameObject("ForgeBench_WorkshopBusinessPanel");DontDestroyOnLoad(g);instance=g.AddComponent<WorkshopBusinessPanel>();}instance.page=Mathf.Clamp(p,0,2);instance.Show();}
        private void Awake(){if(instance!=null&&instance!=this){Destroy(gameObject);return;}instance=this;DontDestroyOnLoad(gameObject);font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");EnsureEventSystem();Build();root.SetActive(false);}
        private void Update(){if(root!=null&&root.activeSelf&&Input.GetKeyDown(KeyCode.Escape)&&!Application.isMobilePlatform)Close();}
        private void Show(){game=GameRuntime.Instance;root.SetActive(true);Cursor.lockState=CursorLockMode.None;MobileInputState.Move=Vector2.zero;Refresh();}
        private void Close(){root.SetActive(false);Cursor.lockState=CursorLockMode.Locked;}
        private void Build()
        {
            root=new GameObject("BusinessRoot",typeof(RectTransform));root.transform.SetParent(transform,false);Canvas c=root.AddComponent<Canvas>();c.renderMode=RenderMode.ScreenSpaceOverlay;c.sortingOrder=25200;CanvasScaler sc=root.AddComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1920,1080);sc.matchWidthOrHeight=.5f;root.AddComponent<GraphicRaycaster>();
            GameObject bg=UI("BG",root.transform);Stretch(bg.GetComponent<RectTransform>());bg.AddComponent<Image>().color=new Color(.015f,.022f,.030f,.99f);GameObject panel=UI("Panel",bg.transform);RectTransform pr=panel.GetComponent<RectTransform>();pr.anchorMin=new Vector2(.06f,.055f);pr.anchorMax=new Vector2(.94f,.945f);pr.offsetMin=pr.offsetMax=Vector2.zero;panel.AddComponent<Image>().color=new Color(.052f,.064f,.080f,1f);
            GameObject header=UI("Header",panel.transform);RectTransform hr=header.GetComponent<RectTransform>();hr.anchorMin=new Vector2(0,1);hr.anchorMax=new Vector2(1,1);hr.pivot=new Vector2(.5f,1);hr.sizeDelta=new Vector2(0,82);hr.anchoredPosition=Vector2.zero;header.AddComponent<Image>().color=new Color(.07f,.085f,.105f,1f);Text title=Text("WORKSHOP MANAGEMENT",header.transform,30,TextAnchor.MiddleLeft,Color.white);RectTransform tr=title.rectTransform;tr.anchorMin=new Vector2(.025f,0);tr.anchorMax=new Vector2(.42f,1);tr.offsetMin=tr.offsetMax=Vector2.zero;
            string[] tabs={"BUSINESS","STAFF","WAREHOUSE"};for(int i=0;i<tabs.Length;i++){int capture=i;Button b=Button(tabs[i],header.transform,new Color(.12f,.15f,.19f,1f),()=>{page=capture;Refresh();});RectTransform r=b.GetComponent<RectTransform>();float x=.46f+i*.13f;r.anchorMin=new Vector2(x,.16f);r.anchorMax=new Vector2(x+.12f,.84f);r.offsetMin=r.offsetMax=Vector2.zero;}Button close=Button("✕",header.transform,new Color(.55f,.11f,.12f,1f),Close);RectTransform xr=close.GetComponent<RectTransform>();xr.anchorMin=new Vector2(.91f,.16f);xr.anchorMax=new Vector2(.975f,.84f);xr.offsetMin=xr.offsetMax=Vector2.zero;
            GameObject scrollGo=UI("Scroll",panel.transform);RectTransform sr=scrollGo.GetComponent<RectTransform>();sr.anchorMin=new Vector2(.02f,.025f);sr.anchorMax=new Vector2(.98f,.90f);sr.offsetMin=sr.offsetMax=Vector2.zero;ScrollRect scroll=scrollGo.AddComponent<ScrollRect>();scroll.horizontal=false;scroll.scrollSensitivity=42f;GameObject viewport=UI("Viewport",scrollGo.transform);Stretch(viewport.GetComponent<RectTransform>());Image vi=viewport.AddComponent<Image>();vi.color=new Color(.024f,.032f,.042f,.78f);Mask mask=viewport.AddComponent<Mask>();mask.showMaskGraphic=false;scroll.viewport=viewport.GetComponent<RectTransform>();GameObject body=UI("Content",viewport.transform);content=body.GetComponent<RectTransform>();content.anchorMin=new Vector2(0,1);content.anchorMax=new Vector2(1,1);content.pivot=new Vector2(.5f,1);content.sizeDelta=new Vector2(0,500);VerticalLayoutGroup vg=body.AddComponent<VerticalLayoutGroup>();vg.padding=new RectOffset(20,20,18,22);vg.spacing=11;vg.childControlHeight=true;vg.childForceExpandHeight=false;vg.childControlWidth=true;vg.childForceExpandWidth=true;ContentSizeFitter fit=body.AddComponent<ContentSizeFitter>();fit.verticalFit=ContentSizeFitter.FitMode.PreferredSize;scroll.content=content;
        }
        private void Refresh()
        {
            if(content==null)return;for(int i=content.childCount-1;i>=0;i--)Destroy(content.GetChild(i).gameObject);game=GameRuntime.Instance;if(game==null)return;WorkshopBusinessService s=game.Business();
            Heading(page==0?"FINANCE / OPERATIONS":page==1?"WORKSHOP STAFF":"WAREHOUSE / USED PARTS","Day "+game.State.day+" · cash $"+game.State.money.ToString("0")+" · reputation "+game.State.reputation);
            if(page==0)RenderBusiness(s);else if(page==1)RenderStaff(s);else RenderWarehouse(s);
        }
        private void RenderBusiness(WorkshopBusinessService s)
        {
            WorkshopState w=game.State.workshop;Card("WORKSHOP LEVEL "+w.level,"Bench "+w.benchLevel+" · storage "+w.storageLevel+" · diagnostics "+w.diagnosticsLevel+" · board repair "+w.boardRepairLevel+"\nCleanliness "+Mathf.RoundToInt(w.cleanliness*100)+"% · receiving automation "+On(w.deliveryAutomation)+"\nDaily overhead $"+s.DailyOverhead.ToString("0")+" including payroll $"+s.DailyPayroll.ToString("0"),Color.white);
            Row("OPERATIONS",new[]{A("UPGRADE WORKSHOP",()=>game.UpgradeWorkshop()),A("TOGGLE RECEIVING AUTO",()=>game.BusinessToggleAutomation()),A("STAFF CLEANING",()=>game.BusinessImproveCleanliness())});
            if(game.State.ledger.Count>0){Section("RECENT LEDGER");foreach(LedgerEntry e in game.State.ledger.AsEnumerable().Reverse().Take(14))Card("Day "+e.day+" · "+e.reason,(e.amount>=0?"+":"")+"$"+e.amount.ToString("0.00")+" → $"+e.balanceAfter.ToString("0.00"),e.amount>=0?new Color(.20f,.82f,.48f,1f):Color.white);}
        }
        private void RenderStaff(WorkshopBusinessService s)
        {
            WorkshopState w=game.State.workshop;Card("TEAM","Helpers "+w.helperStaff+" · specialists "+w.specialistStaff+"\nPayroll $"+s.DailyPayroll.ToString("0")+" / day\nHelpers expand receiving/storage throughput. Specialists raise advanced repair capability.",Color.white);
            Row("HIRING",new[]{A("HIRE HELPER",()=>game.BusinessHireHelper()),A("HIRE SPECIALIST",()=>game.BusinessHireSpecialist()),A("RELEASE HELPER",()=>game.BusinessFireHelper()),A("RELEASE SPECIALIST",()=>game.BusinessFireSpecialist())});
        }
        private void RenderWarehouse(WorkshopBusinessService s)
        {
            float u=s.Utilization;Color c=u>.9f?new Color(.95f,.34f,.24f,1f):u>.72f?new Color(.95f,.68f,.22f,1f):new Color(.20f,.82f,.48f,1f);Card("WAREHOUSE CAPACITY",s.WarehouseUsed+" / "+s.WarehouseCapacity+" slots · "+Mathf.RoundToInt(u*100)+"% used\nStorage level "+game.State.workshop.storageLevel+" · helper capacity bonus "+(game.State.workshop.helperStaff*8),c);
            Section("UNRESERVED WORKSHOP INVENTORY");foreach(ItemInstance item in s.SaleCandidates(30)){HardwareDefinition d=game.Inventory.Def(item);if(d==null)continue;GameObject row=UI("InventoryRow",content);row.AddComponent<Image>().color=new Color(.10f,.12f,.15f,1f);HorizontalLayoutGroup h=row.AddComponent<HorizontalLayoutGroup>();h.padding=new RectOffset(15,10,8,8);h.spacing=9;h.childControlHeight=true;h.childForceExpandHeight=true;LayoutElement rl=row.AddComponent<LayoutElement>();rl.preferredHeight=72;GameObject text=UI("Text",row.transform);VerticalLayoutGroup tv=text.AddComponent<VerticalLayoutGroup>();tv.childForceExpandHeight=false;LayoutElement tl=text.AddComponent<LayoutElement>();tl.flexibleWidth=1;Text a=Text(d.brand+" "+d.model,text.transform,19,TextAnchor.MiddleLeft,Color.white);a.fontStyle=FontStyle.Bold;Text b=Text("Condition "+Mathf.RoundToInt(item.condition*100)+"% · "+d.category+" · fault "+item.fault+" · damage "+item.damage,text.transform,15,TextAnchor.MiddleLeft,new Color(.63f,.70f,.77f,1f));string id=item.instanceId;Button refurb=Button("REFURBISH",row.transform,new Color(.15f,.39f,.58f,1f),()=>{game.BusinessRefurbish(id);Refresh();});Button sell=Button("SELL",row.transform,new Color(.12f,.52f,.34f,1f),()=>{game.BusinessSell(id);Refresh();});LayoutElement rle=refurb.gameObject.AddComponent<LayoutElement>();rle.preferredWidth=150;LayoutElement sle=sell.gameObject.AddComponent<LayoutElement>();sle.preferredWidth=110;}
        }
        private struct Act{public string l;public Action a;public Act(string x,Action y){l=x;a=y;}}private static Act A(string l,Action a)=>new Act(l,a);private static string On(bool v)=>v?"ON":"OFF";
        private void Heading(string a,string b){Text t=Block(a,32,Color.white,55);t.fontStyle=FontStyle.Bold;Block(b,19,new Color(.56f,.65f,.73f,1f),38);}private void Section(string a){Text t=Block(a,22,new Color(.10f,.64f,.92f,1f),42);t.fontStyle=FontStyle.Bold;}
        private void Card(string title,string sub,Color c){GameObject g=UI("Card",content);g.AddComponent<Image>().color=new Color(.095f,.115f,.145f,1f);VerticalLayoutGroup v=g.AddComponent<VerticalLayoutGroup>();v.padding=new RectOffset(18,18,11,12);v.spacing=4;v.childControlHeight=true;v.childForceExpandHeight=false;LayoutElement le=g.AddComponent<LayoutElement>();le.minHeight=70;Text a=Text(title,g.transform,21,TextAnchor.MiddleLeft,c);a.fontStyle=FontStyle.Bold;Text b=Text(sub,g.transform,17,TextAnchor.UpperLeft,new Color(.66f,.73f,.80f,1f));b.horizontalOverflow=HorizontalWrapMode.Wrap;b.verticalOverflow=VerticalWrapMode.Overflow;}
        private void Row(string title,Act[] actions){Section(title);GameObject g=UI("Actions",content);HorizontalLayoutGroup h=g.AddComponent<HorizontalLayoutGroup>();h.spacing=9;h.childControlHeight=true;h.childForceExpandHeight=true;h.childForceExpandWidth=true;LayoutElement le=g.AddComponent<LayoutElement>();le.preferredHeight=60;foreach(Act a in actions){Button b=Button(a.l,g.transform,new Color(.11f,.38f,.59f,1f),()=>{a.a?.Invoke();Refresh();});LayoutElement bl=b.gameObject.AddComponent<LayoutElement>();bl.flexibleWidth=1;}}
        private Text Block(string value,int size,Color c,float height){Text t=Text(value,content,size,TextAnchor.MiddleLeft,c);LayoutElement l=t.gameObject.AddComponent<LayoutElement>();l.preferredHeight=height;return t;}private Button Button(string label,Transform p,Color c,Action a){GameObject g=UI("Button_"+label,p);Image i=g.AddComponent<Image>();i.color=c;Button b=g.AddComponent<Button>();b.targetGraphic=i;if(a!=null)b.onClick.AddListener(()=>a());Text t=Text(label,g.transform,16,TextAnchor.MiddleCenter,Color.white);Stretch(t.rectTransform,5);t.raycastTarget=false;return b;}private Text Text(string value,Transform p,int size,TextAnchor align,Color c){GameObject g=UI("Text",p);Text t=g.AddComponent<Text>();t.font=font;t.text=value;t.fontSize=size;t.alignment=align;t.color=c;t.raycastTarget=false;return t;}private GameObject UI(string n,Transform p){GameObject g=new GameObject(n,typeof(RectTransform));g.transform.SetParent(p,false);return g;}private static void Stretch(RectTransform r,float i=0){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=new Vector2(i,i);r.offsetMax=new Vector2(-i,-i);}private static void EnsureEventSystem(){if(FindAnyObjectByType<EventSystem>()!=null)return;GameObject e=new GameObject("EventSystem");e.AddComponent<EventSystem>();e.AddComponent<StandaloneInputModule>();DontDestroyOnLoad(e);}
    }
}
